name: ${project.name}
version: ${project.version}
main: com.hackquest.shenlong55.survivaloptions.SurvivalOptionsPlugin
author: shenlong55
description: ${project.description}
api-version: 1.15
commands: null